[#ftl]
[@b.head/]
[@b.toolbar title="修改学生请假信息"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action=b.rest.save(stdLeave) theme="list"]
    [@base.student name="stdLeave.std.id" label="学生" value=stdLeave.std /]
    [@b.radios  label="类别" name="stdLeave.leaveType" items={"0":'事假',"1":'病假',"2":'公假'} required="true" value=(stdLeave.leaveType.id?string)!"0"/]
    [@b.startend name="stdLeave.beginAt,stdLeave.endAt" label="请假时间" start=stdLeave.beginAt! end=stdLeave.endAt!
           style="width:200px;" required="true" format="yyyy-MM-dd HH:mm:ss"/]
    [@b.textarea name="stdLeave.reason" label="事由" value=stdLeave.reason! required="true" maxlength="100" cols="80" rows="4"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
